#cloud-config


package_update: true
packages:
  - nginx


write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
        listen        80 default_server;
        location / {
          proxy_pass         http://10.0.0.12:5000/;
          proxy_http_version 1.1;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection keep-alive;
          proxy_set_header   Host $host;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
        }
      }

runcmd:
  - |
    systemctl reload nginx
    