#cloud-config

write_files:
  - path: /etc/Todo/Todo.env
    content: |
      AzureCosmosDBTodoService__ConnectionString=empty
      AzureCosmosDBTodoService__Database=TodoDB
      AzureCosmosDBTodoService__Collection=TodoList

  - path: /etc/systemd/system/Todo.service
    content: |
      [Unit]
      Description=ASP.NET Web App running on Ubuntu

      [Service]
      WorkingDirectory=/opt/Todo
      ExecStart=/usr/bin/dotnet /opt/Todo/Todo.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=Todo
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      Environment=ASPNETCORE_URLS=http://*:5000
      EnvironmentFile=/etc/Todo/Todo.env

      [Install]
      WantedBy=multi-user.target

systemd:
  units:
    - name: Todo.service
      enabled: true


runcmd:
  - |
    declare repo_version=$(if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi)
    
    wget https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

    dpkg -i packages-microsoft-prod.deb

    rm packages-microsoft-prod.deb

    apt update

    apt-get update 
    
    apt-get install -y aspnetcore-runtime-8.0

    mkdir /home/azureuser/actions-runner; cd /home/azureuser/actions-runner

    curl -o actions-runner-linux-x64-2.314.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.314.1/actions-runner-linux-x64-2.314.1.tar.gz

    tar xzf ./actions-runner-linux-x64-2.314.1.tar.gz

    chown -R azureuser:azureuser /home/azureuser/actions-runner
    
    sudo -u azureuser ./config.sh --unattended --url https://github.com/houbou98-19/Todo --token AM67RNTC7X4PVRA7CDLNCT3F7WT72 --name Todo

    ./svc.sh install azureuser

    ./svc.sh start

    systemctl daemon-reload
    systemctl enable Todo.service
    systemctl start Todo.service

